name: sonix
description: "Flutter audio waveform package with multi-format support (MP3, WAV, FLAC, OGG, Opus, MP4, M4A) using FFMPEG."
version: 1.0.0
homepage: https://github.com/zooper-lib/Sonix
repository: https://github.com/zooper-lib/Sonix
issue_tracker: https://github.com/zooper-lib/Sonix/issues
documentation: https://pub.dev/documentation/sonix/latest/

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.8.3
  meta: ^1.15.0
  crypto: ^3.0.3
  archive: ^3.4.10
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^13.0.0
  test: ^1.24.0

executables:
  setup_ffmpeg_for_app: setup_ffmpeg_for_app

flutter:
  plugin:
    platforms:
      android:
        package: dev.zooper.sonix
        pluginClass: SonixPlugin
      ios:
        pluginClass: SonixPlugin
      linux:
        pluginClass: SonixPlugin
      macos:
        pluginClass: SonixPlugin
      windows:
        pluginClass: SonixPlugin
